openapi: 3.0.1
info:
  title: Account Service API
  version: 1.0.0
  description: API para la gestión de cuentas de usuarios del sistema.

servers:
  - url: http://localhost:8080/api/accounts

paths:

  /:
    post:
      summary: Crear una cuenta
      description: Crea una nueva cuenta para un usuario.
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/AccountRequestDTO"
      responses:
        "200":
          description: Cuenta creada correctamente.
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/AccountResponseDTO"

    get:
      summary: Listar cuentas
      description: Devuelve todas las cuentas, con opción de filtrar por tipo.
      parameters:
        - name: type
          in: query
          required: false
          schema:
            $ref: "#/components/schemas/AccountType"
      responses:
        "200":
          description: Lista de cuentas.
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: "#/components/schemas/AccountResponseDTO"

  /{id}:
    get:
      summary: Obtener cuenta por ID
      parameters:
        - name: id
          in: path
          required: true
          schema: { type: integer }
      responses:
        "200":
          description: Cuenta encontrada
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/AccountResponseDTO"

    delete:
      summary: Eliminar cuenta permanentemente
      parameters:
        - name: id
          in: path
          required: true
          schema: { type: integer }
      responses:
        "200":
          description: Cuenta eliminada
        "404":
          description: La cuenta no existe

  /{id}/recharge:
    post:
      summary: Recargar saldo de una cuenta
      parameters:
        - name: id
          in: path
          required: true
          schema: { type: integer }
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/RechargeRequestDTO"
      responses:
        "200":
          description: Recarga efectuada
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/RechargeResultDTO"

  /{id}/discount:
    post:
      summary: Aplicar un descuento de saldo
      parameters:
        - name: id
          in: path
          required: true
          schema: { type: integer }
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/DiscountRequestDTO"
      responses:
        "200":
          description: Descuento aplicado
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/DiscountResultDTO"

  /set-status/{id}:
    put:
      summary: Cambiar estado de una cuenta
      description: Permite habilitar o inhabilitar cuentas temporalmente.
      parameters:
        - name: id
          in: path
          required: true
          schema: { type: integer }
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/StatusUpdateRequestDTO"
      responses:
        "200":
          description: Estado actualizado
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/AccountResponseDTO"

components:

  schemas:

    AccountType:
      type: string
      enum: [USER, ADMIN]

    AccountRequestDTO:
      type: object
      properties:
        username:
          type: string
        type:
          $ref: "#/components/schemas/AccountType"
        initialBalance:
          type: number

    AccountResponseDTO:
      type: object
      properties:
        id:
          type: integer
        username:
          type: string
        type:
          $ref: "#/components/schemas/AccountType"
        balance:
          type: number
        status:
          type: string
          enum: [ACTIVE, INACTIVE]

    RechargeRequestDTO:
      type: object
      properties:
        amount:
          type: number

    RechargeResultDTO:
      type: object
      properties:
        accountId:
          type: integer
        newBalance:
          type: number

    DiscountRequestDTO:
      type: object
      properties:
        amount:
          type: number

    DiscountResultDTO:
      type: object
      properties:
        accountId:
          type: integer
        newBalance:
          type: number

    StatusUpdateRequestDTO:
      type: object
      properties:
        status:
          type: string
          enum: [ACTIVE, INACTIVE]
